---
driver:
  name: vagrant
  box_download_insecure: true
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[owi_docker::docker_service]
      - recipe[owi_docker::docker_machine]
      - recipe[owi_docker::docker_compose]
    verifier:
      inspec_tests:
        - name: centos7
          path: ./test/integration/centos7/inspec
